.travis.yml, cmp/compare.go, cmp/compare_test.go, cmp/example_test.go, cmp/options_test.go, cmp/reporter.go
Avoid any features introduced in newer versions such as:
* testing.T.Run
* sort.Slice
* sort.SliceStable
* sort.IsSliceSorted
Fixes #2
=> Support versions of Go down to Go1.6

cmp/options.go, cmp/unsafe_panic.go, cmp/unsafe_reflect.go
Rather than waiting until the unsafeRetrieveField helper
function is actually called, panic at the moment someone tries
to use AllowUnexported to make the failure more obvious.
=> Make lack of support for AllowUnexported more obvious

cmp/options.go
At this point, we will not be removing the AllowUnexported option
as there are several use-cases that legitimately benefit from it.
Also, the current documentation does a good job of explaining
what the proper use of it is. Thus, remove the warning as it is
unhelpful and confusing to users.
The other (unlikely) alternative I can see in the future is to
make AllowUnexported the default behavior for all comparisons
effectively making AllowUnexported a noop. That would be a
backwards compatible change.
=> Remove warning about status of AllowUnexported

cmp/path.go
It is very common for FilterPath functions to operate on the last step
in a path. However, it is a hindrance to continually write:
if len(p) == 0 {
return false
}
return p[len(p)-1].Type() == ...
Instead, add a helper method Last that avoids the empty path check
and the indexing to the last element.
This allows users to simply write:
return p.Last().Type() == ...
This is more readable and writeable.
=> Add Last helper method

cmp/cmpopts/equate.go, cmp/cmpopts/ignore.go, cmp/cmpopts/sort.go, cmp/cmpopts/sort_go17.go, cmp/cmpopts/sort_go18.go, cmp/cmpopts/struct_filter.go, cmp/cmpopts/util_test.go, cmp/example_test.go, cmp/options.go
This adds the following API surface:
func EquateApprox(fraction, margin float64) cmp.Option
func EquateEmpty() cmp.Option
func EquateNaNs() cmp.Option
func IgnoreFields(typ interface{}, names ...string) cmp.Option
func IgnoreInterfaces(ifaces interface{}) cmp.Option
func IgnoreTypes(typs ...interface{}) cmp.Option
func IgnoreUnexported(typs ...interface{}) cmp.Option
func SortMaps(less interface{}) cmp.Option
func SortSlices(less interface{}) cmp.Option
Reviewed-By: bcmills@google.com
=> Add cmpopts helper package

cmp/compare.go
Users find it unhelpful to simply panic saying that unexported fields
cannot be handled. Augment the panic message by pointing the user
to functions that can be used to address the issue.
=> Add helpful suggestions to panic message

.travis.yml
The default test script is `go test -v ./...` (assuming a Makefile is not present) according to Travis docs at https://docs.travis-ci.com/user/languages/go/#Default-Test-Script.
Add an additional gofmt check to help catch formatting issues in PRs. This is motivated by a previous occurrence at https://github.com/google/go-cmp/pull/9#discussion_r127624347.
Also swap the order of Go versions 1.x and 1.6. 1.x is higher priority, so it makes more sense to run it first and report issues right away. 1.6 is lower priority, so it's better to prioritize it lower.
Use 2 space indent in the .yml file, which is consistent with the formatting in Travis documentation and examples.
/cc @dsnet
=> Travis: Check for gofmt issues.

.travis.yml, cmp/cmpopts/sort_go18.go, cmp/cmpopts/util_test.go, cmp/compare_test.go
This change augments the Travis CI build to perform:
-	Include `-s` (simplify) flag when checking that all files follow `gofmt` style.
-	Check that `go vet` does not report any problems.
-	Use race detector when running tests, to help catch data races.
-	Include a fast-finish allowed failure build on `master` (tip). Due to a chance of false positives, failures on tip are not critical, but manually looking over them can help spot issues either in this project, or in the tip version of Go.
Resolves #13. /cc @dsnet
=> Travis: Run go vet; use race detector during tests.

cmp/compare.go
State that a non-nil empty slice is not equal to a nil slice.
Suggest use of cmpopts.EquateEmpty to handle this case.
Fixes #18
=> Clarify documentation regarding empty slices and maps

cmp/compare.go, cmp/compare_test.go, cmp/internal/diff/debug_disable.go, cmp/internal/diff/debug_enable.go, cmp/internal/diff/diff.go, cmp/internal/diff/diff_test.go, cmp/path.go, cmp/reporter.go
This adds an internal package with the following API:
func Difference(nx, ny int, f EqualFunc) (eq bool, es EditScript)
type EditScript []EditType
type EditType int8
const Identity EditType = iota ...
type EqualFunc func(ix int, iy int) Result
type Result struct{ ... }
The cmp.SliceIndex type has a new method SplitKeys to indicate that
elements are being compared in x and y are in different indexes.
The debug visualizer can be run:
go test -tags=debug -v github.com/google/go-cmp/cmp/internal/diff
Reviewed-By: dneil@google.com
=> Add diffing abilities to reporting

cmp/options.go, cmp/reporter.go
The default reporter won't be adding context for equal values.
Instead, we should work on the API for registering custom reporters.
=> Remove reporter TODO

cmp/compare_test.go, cmp/internal/value/format.go
There was a bug in the way this package handles nil Stringer values.  This diff fixes the bug, and adds a previously failing test.
=> Fix Bug With Nil Stringers

cmp/compare.go, cmp/compare_test.go
A copying-append runs in O(n) where n is the number of options.
Instead, just create a new Options group, which is O(1).
Also switch the tests to run in parallel to increase chances of
detecting races.
=> Use an Options group instead of copying-append

cmp/cmpopts/sort.go, cmp/compare.go, cmp/internal/function/func.go, cmp/options.go
Unify the common logic for identifying the type of function.
This logic is helpful since Go lacks generics, so it is hard for example
to query whether a function is of the signature: func(T, T) bool
=> Add cmp/internal/function package

cmp/compare.go, cmp/compare_test.go, cmp/options.go, cmp/options_test.go
The previous implementation of options had a single type "option"
that was used to represent either an Ignore, Comparer, or Transformer
and all of the filters relevant to each of them.
We refactor this logic by creating a new type to represent each
fundamental option and each filtering option. Construction of
filtered options is now as simple as wrapping the input option with
the appropriate filter type.
Evaluation of filters now takes a top-down approach where each of
the options now have a filter method and know how to filter themselves
and recursively call filter on the any sub-options.
This approach has the following advantages:
* It is faster because the same filter that was applied to multiple
options now only needs to execute once.
* Even though this is semantically identical, the …
=> Refactor option evaluation logic

cmp/internal/value/sort.go, cmp/internal/value/sort_test.go
Avoid using reflect.Value.Interface to de-duplicate keys since
some keys may have source from an unexported field,
causing the logic to panic. Instead, just rely on the isLess function,
which is already safe to use on unexported values.
Fixes #38
=> Fix panic in sort.go

cmp/compare.go
The go/doc package requires a UID to be present in order to detect
package level annotations.
See https://golang.org/pkg/go/doc#Note
=> Add UID to BUG note

cmp/internal/value/format.go, cmp/internal/value/format_test.go
The format logic should work even if the reflect.Value is in RO mode.
=> Test unexported field access in format logic

cmp/compare_test.go, cmp/path.go
Many of the powerful uses of Transformers produces a significant amount of
interfaces to anonymous types. For example, a generic JSON unmarshaler
can unmarshal into a map[string]interface{} or []interface{}.
However, the printing of these type assertions can be really noisy.
Thus, elide type assertions for these cases.
=> Elide printing type assertions on unnamed types

cmp/compare.go, cmp/compare_test.go, cmp/internal/diff/diff.go, cmp/internal/diff/diff_test.go
Rather than performing the heuristic for whether two slices are
"too different" in the diff package, just return the full edit-script
and move the heuristic logic into the cmp package.
The main adjustment to the heuristic is that we only print the
full slice if it is composed of a slice of primitive types (e.g., []byte)
and the difference between the two slices is sufficiently great enough.
Fixes #44
=> Change diff.Difference to always return an edit-script

cmp/compare_test.go, cmp/internal/value/format.go, cmp/internal/value/format_test.go
When formatting strings, avoid using strconv.Quote if the string looks
like it has already been escaped. Instead, use a raw string literal
by wrapping the string with '`' characters if possible.
For now, we still use strconv.Quote if the input string contains newlines
to maintain the property that Format outputs a single line.
Also, prefix strings obtained by the Stringer.String method with a 's'.
This allows users to more easily distinguish when an output really is
of type string or if the String method was used.
=> Use raw literal for string formatting

cmp/reporter.go
The defaultReporter.ndiffs field holds the total number of differences,
while the diffs fields holds a truncated list of differences.
The subtraction math is backwards, resulting in a negative count.
=> Fix reporter difference count

cmp/compare.go, cmp/compare_test.go
The reflect package has a bug (golang/go#22143).
Let R and T both be interface types and R be assignable to T.
Let F be a function that takes T as its argument.
The Go language lets you directly call F with a nil T or a nil R
(since R is assignable to T) without any special handling.
Currently, reflect allows you to call F with a nil T,
but panics when calling F with a nil R. To avoid this panic,
we explicitly check for the condition where a value:
* is an interface type
* is nil
* is not exactly same as type T
and re-create the value as a nil interface of type T.
=> Explicitly convert assignable nil interface values

cmp/compare_test.go, cmp/example_test.go, cmp/options.go
Declaring a transformer "func(T) T" where T is a concrete type
is a common transformation. However, this is currently problematic
as the transformation now infinitely applies to itself recursively.
In order to allow this form of transformation, add a simple
(but subtle) filter to Transformers where a Transformer can only
apply if that specific Transformer does not already exist within
the tail of the current Path since the last non-Transform step.
This rule does not prevent more advance usages of Transformers
where the user *does* want the Transformer to apply recursively
to previously transformed output, since those situations are
almost always followed by some path step that is *not* a
transformation (e.g., pointer indirect, slice indexing, etc).
Fixes #17
Fixes #51
=> Add implicit filter to Transformers

cmp/compare.go, cmp/options.go
For all implementations of apply, it either returns true or panics.
Thus, the bool return value is a useless piece of information.
=> Remove useless return value from applicableOption.apply

cmp/compare_test.go, cmp/path.go
Currently there is no easy way to create non-reentrant transformers
where they do not recursively apply on their own output.
You could check for the Transformer name, but the API does not
require the names to be unique.
The only way to write a helper to do this is to generate some obscure
name that is guaranteed to probabilistic never have a conflict.
A better approach is to simply return the original Option
as returned by the Transformer constructor.
Thus, users can rely on == to check if a Transform step exactly
matches a Transformer that they created.
It would be useful to a non-reentrant transformer to cmpopts,
but that can be a future addition. It will also need a better name.
=> Add Transform.Option helper method

.travis.yml, cmp/compare_test.go, cmp/internal/teststructs/project3.go
Rather than running gofmt for every version, leading to version skew
when what gofmt considers "correct" differs between versions,
only use one specific version of gofmt.
Also, remove the "-s" flag from gofmt because it is not backwards compatible.
Suppose Go1.11 allowed for elliding types on struct literals and the "-s"
flag strips them, then this would be problematic because it would not compile
on Go1.10 and earlier.
Also, fix the code so that vet is happy. I am not sure why these checks
were not triggered before. There seems to be a bug in the caching of
$GOPATH/pkg files. This may be fixed in Go1.10 by the new caching logic.
Running "go install" before running go vet fixes the issue.
In other words, the only check we perform for differing versions
is that the tests pass (and …
=> Adjust Travis CI script

cmp/compare_test.go, cmp/internal/value/format.go, cmp/internal/value/format_test.go, cmp/reporter.go
When the formatted strings are identical, the reporter tries to fallback
on more exact formatting. This fallback should include the types for
primitive types since the difference can simply be between
an int and an uint.
Fixes #64
=> Report with primitive types in diffs

cmp/options.go, cmp/unsafe_panic.go, cmp/unsafe_reflect.go
The proposal in golang/go#23172 was accepted. The "purego" build tag
is intended to be a community agreed upon soft-signal to indicate the
forbidden use of unsafe, assembly, or cgo.
A change in the future will remove special-casing the appengine and js tags
once the related toolchains support purego (possibly after some bake-in period).
=> Support purego build tag

cmp/cmpopts/util_test.go
To prevent future developers from getting lazy,
check that a reason is given as part of each test case.
Checks are only given for cmpopts.
The cmp tests lack reasons, which is future work.
=> Enforce tests to provide a reason

cmp/cmpopts/util_test.go, cmp/cmpopts/xform.go, cmp/options.go
Add AcyclicTransformer helper, which wraps Transformer with a FilterPath
that ensures that the transformer cannot be recursively applied upon
the output of itself. Adjust documentation of Transformer to suggest usage
of AcyclicTransformer if necessary.
Fixes #77
=> Add AcyclicTransformer helper

cmp/compare.go, cmp/compare_test.go
Check for probable infinite recursive cycles
After some hard-coded limit, check the path for recursive transformers.
Note that detecting an infinite cycle of recursive transformers
would be equivalent to solving the halting problem,
so we could misdiagnose a valid recursion as infinite.
For this reason, the check only triggers after some minimum stack size
so that correctness is not compromised for nearly all situations.
However, the threshold is low enough to trigger before the Go runtime
panics with a stack overflow (which is not recoverable).
Example panic message:
```
panic: recursive set of Transformers detected:
Transformer(T1, main.main.func1): complex64 => complex128
Transformer(T2, main.main.func2): complex128 => [2]float64
Transformer(T3, main.main.func3): float64 => complex64 …
```
=> Check for probable infinite recursive cycles

cmp/internal/value/format.go, cmp/internal/value/format_test.go, cmp/internal/value/pointer_purego.go, cmp/internal/value/pointer_unsafe.go
The cycle detection in value.Format uses a map of uintptrs, which is not
correct as this assumes that the Go GC never uses a moving collector.
Instead, we should be using unsafe.Pointer, which the GC knows how to scan.
Also, push pointer checking of slices down to the level of individual elements.
We do this because the slice pointer is not sufficient to determine equality.
For example, v[:0] and v[:1] both have the same slice pointer, but are
clearly different values.
Since the purego environment forbids the use of unsafe, create a Pointer type
that is an abstraction over an opaque pointer. The Pointer type can only be
compared. In the purego, continue to use uintptr, which is the best we can do.
=> Fix cycle detection in internal/value.Format

go.mod
Go 1.11 is now released with preliminary support for Go modules.
If a repository is checked outside of the GOPATH, then the Go toolchain will
use the module support by default. However, it requires a go.mod file so that
the toolchain can derive the import paths of all packages living under the
tree containing the go.mod file.
=> go.mod: add module file

cmp/unsafe_panic.go, cmp/unsafe_reflect.go
The purego tag should cover all environments (e.g., gopherjs and appengine)
that do not support unsafe.
=> Remove special-case build tags

cmp/internal/diff/debug_disable.go, cmp/internal/diff/debug_enable.go, cmp/internal/diff/diff.go
Switch the build tag for debugging from "debug" to "cmp_debug".
The former tag accidentally matches usages of that tag for unrelated projects.
Fixes #104
=> Make debug mode more explicit

cmp/compare.go, cmp/internal/function/func.go, cmp/internal/function/func_test.go, cmp/options.go
Adjust the logic of NameOf for more recent versions of Go.
=> Move function name logic to function package

cmp/compare.go, cmp/compare_test.go
The _ field in Go is special in that it cannot be read from or written to.
Thus, skip it by default. It is pointless to require the user to use
cmpopts.IgnoreUnexported just for the _ field.
=> Always ignore _ fields

cmp/options.go, cmp/options_test.go, cmp/path.go
Relax the Transformer name to be any Go identifier or qualified identifier.
Clarify in the documentation how this is used (e.g., in Diff) and
what names are valid.
Fixes #102
=> Relax Transformer name rules

cmp/compare.go, cmp/path.go
Reorder logic to consistently handle steps in the order of:
StructField, SliceIndex, MapIndex, Indirect, TypeAssertion
=>  Reorder logic to be consistent

cmp/cmpopts/sort.go, cmp/compare_test.go, cmp/options.go
If the name is unspecified, try to derive the name from the function pointer.
Deriving the name from the function pointer is not always reliable
since it relies on runtime properties that are not specified to be stable.
=> Derive the default transformer name from the function pointer

cmp/compare.go, cmp/compare_test.go, cmp/options.go, cmp/report.go
Switch the internal interface for reporting to use a push-pop mechanism.
This API is strictly more flexible than the previous Report-only API since it
enables the reporter to re-construct the entire value tree.
This change is done in preparation for a major overhaul of reporter logic.
=> Refactor reporter implementation

cmp/compare.go, cmp/export_panic.go, cmp/export_unsafe.go
Rename the file based on what it does rather than how its implemented.
=> Rename unsafe_x.go as export_x.go

cmp/compare.go, cmp/compare_test.go, cmp/options.go, cmp/path.go, cmp/report.go, go.mod
Some of the value information is already in the path (e.g., MapIndex.Key
and SliceIndex.Key), which seems to suggest that all of the value information
should be in the Path. Doing so has several benefits:
* It simplifies the comparison logic
* It paves the way for FilterPath to be able to ignore missing
slice elements or map entries
* It allows for a simpler API for custom reporters
One regression introduced by this change is the removal of batching for
slices when sufficient number of elements differ. This logic was added
as a hack in the past to keep the reporter output small in such cases.
However, this batching functionality should be the responsibility of the
reporter logic, not the comparer logic. A future change will refactor
the reporter logic to reintroduce that feature.
=> Add Values method to PathStep

cmp/compare.go, cmp/options.go, cmp/options_test.go, cmp/report.go
This is necessary for the upcoming reporter re-implementation so that
it can format the differences with more intelligence.
No tests added in this PR since an upcoming change will heavily test
these code paths.
=> Augment Report to indicate how comparison was determined

cmp/compare.go, cmp/compare_test.go, cmp/options.go, go.mod
Rather than checking up-front whether the values are invalid,
give tryOptions a chance to operate on them and potentially ignore
the values. This is useful since a value can only be invalid if it
is a missing slice element or map entry, and provides FilterPath
combined with Ignore the ability to ignore such cases.
Some complexity is added to compareSlice to look for ignored elements
first before applying diffing so that we can decouple the stability
of the diffing algorithm from the primary result.
=> Evaluate options even if values are invalid

cmp/compare_test.go
Add a benchmark that uses cmp.{Equal,Diff} to measure performance of
comparing large byte slices. Comparing large slices of primitives is
generally considered the most pathological use-case for cmp since the
rules of cmp dictate that it must run the filters on every element
of the slice even if the filters never apply.
In theory, a user of cmp could short-circuit comparison of slices by
providing a comparer for slices (e.g., cmp.Comparer(bytes.Equal)),
but it would be ideal for cmp to be sufficiently optimized that comparing
large slices is not too costly.
BenchmarkBytes/4KiB/EqualFilter0-4         	     300	   3792755 ns/op	   2.16 MB/s	  628702 B/op	    8276 allocs/op
BenchmarkBytes/4KiB/EqualFilter1-4         	     200	   6058637 ns/op	   1.35 MB/s	  890920 B/op	   16471 allocs/op …
=> Add BenchmarkBytes

cmp/compare.go, cmp/options.go
Avoid appending validator in every call to tryOptions and
instead ensure that the state starts with one in the options list.
Doing so dramatically reduces the number of allocations.
```
benchmark                               old MB/s     new MB/s     speedup
BenchmarkBytes/4KiB/EqualFilter0-4      2.16         2.56         1.19x
BenchmarkBytes/4KiB/EqualFilter1-4      1.35         1.53         1.13x
BenchmarkBytes/4KiB/EqualFilter2-4      1.09         1.20         1.10x
BenchmarkBytes/4KiB/EqualFilter3-4      0.81         0.99         1.22x
BenchmarkBytes/4KiB/EqualFilter4-4      0.74         0.77         1.04x
BenchmarkBytes/4KiB/EqualFilter5-4      0.63         0.69         1.10x
BenchmarkBytes/4KiB/DiffFilter0-4       2.04         2.38         1.17x
BenchmarkBytes/4KiB/DiffFilter1-4 …
```
=> Add validator option once at state creation

cmp/cmpopts/ignore.go, cmp/options.go
Currently we put push users towards options that handle unexported fields. A common scenario is:
1. someone uses cmp.Diff on big.Int (transitively)
2. they get a message that advertises Ignore/Allow Unexported options
3. they see that AllowUnexported is hard to use correctly
4. they use IgnoreUnexported
They end up with:
cmp.IgnoreUnexported(big.Int{})
Which definitely doesn't do what's intended.
If we point out that a custom comparer is what they most likely need, then they are more likely to use cmp correctly.
=> Nudge people to use custom comparers

cmp/compare.go, cmp/example_reporter_test.go, cmp/options.go, cmp/options_test.go, cmp/report.go, cmp/report_value.go
The Reporter option allows users to hook in their own custom reporters
to programatically interpret the diff structure.
The Reporter API uses a push/pop mechanism, which is strictly more powerful
than an API that only calls report on leaf nodes.
The Reporter.Report method takes in a flag set to provide flexibility in
what properties can be reported in the future since new constants can be added,
but new methods cannot be easily added to the reporter interface.
=> Export the Reporter API

cmp/cmpopts/ignore.go, cmp/cmpopts/sort.go, cmp/cmpopts/util_test.go, cmp/cmpopts/xform.go, cmp/internal/function/func.go
These helper options ignore slice elements or map entries based
on a user-provided predicate function. These are especially useful
for ignoring missing elements or entries.
=> Add IgnoreSliceElements and IgnoreMapEntries helpers

cmp/compare.go, cmp/options.go, cmp/path.go
Rather than representing each path step as an interface,
use concrete types instead. This provides some performance benefits as
it reduces the amount of virtual function calls and also provides the
ability for the compiler to inline method calls.
This is technically a breaking change, but since each of the path step
interfaces were explicitly implemented in such a way that they couldn't
be implemented directly (due to the presence of an unexported method),
the only way someone could have been depending on these as interfaces is
if they embedded the interface into another interface. Static analysis of
all code at Google and publicly available on GitHub shows that this is
not a problem.
The performance benefits of this change is significant:
```
benchmark                               old …
```
=> Use concrete types for path steps

cmp/compare_test.go, cmp/internal/diff/diff.go, cmp/report_compare.go, cmp/report_slices.go
Lists of primitives are a common-enough data structure that
it is worth providing specialized diffing for.
This provides significantly better readability for strings
and byte slices. There is also a heuristic for detecting
what a string should be diffed as a multiline string.
=> Implement specialized diffing for slices

cmp/compare_test.go, cmp/report_reflect.go
This reverts a change introduced in commit 2940eda701 where the
cmp package stopped calling the String method when printing map
keys. The motivation for the change is unclear, indeed there was
a pre-existing test that String was called on map keys that the
commit changed.
Fixes #141
=> Invoke String when formatting map keys 

cmp/report_compare.go
I assume this is a typo, as the left and right side of the boolean-or were
identical. Please thoroughly review this.
=> Fixed typo in formatDiffList

cmp/cmpopts/util_test.go, cmp/report_slices.go, cmp/report_text.go
- No need to wrap ToUpper & Fields
- Simpler concatenation
- Easier pointer access
=> Simplify code

cmp/report_slices.go
Please review this thoroughly, I'm not sure I can properly test this change.
However I noticed that the assignment to lastLineIdx in line 93 is ineffectual,
as it'll always get overwritten in the line below. I can only assume this
either means the else-block was missing (which is what I'm fixing here), or it's
an old check that's just lingering around and was forgotten to be removed during
refactoring.
=> Fix ineffectual assignment to lastLineIdx

cmp/internal/value/sort.go, cmp/internal/value/zero.go, cmp/internal/value/zero_test.go
* Fix IsZero to properly report false for IsZero(-0.0) since
we define IsZero as whether it is equal to the zero memory value.
* Add note to isLess that we don't need to handle -0.0 since
we can't possibly have both keys present in the same map.
* Use sort.SliceStable in SortedKeys for deterministic output since
it is possible to have both -0.0 and +0.0 from two different maps.
The zero key from the left left map will be taken over the right map.
=> cmp/internal/value: fix handling of negative zero for floats

cmp/export_unsafe.go
=> cmp: make retrieveUnexportedField pass Go 1.14's upcoming checkptr validation

cmp/compare_test.go, cmp/options.go
In the panic message when accessing an unexported field,
print the full name of the type for user convenience.
=> Print type name in unexported panic

cmp/compare.go, cmp/export_panic.go, cmp/export_unsafe.go, cmp/options.go, cmp/path.go
Add an Exporter option that accepts a function to determine
which struct types to permit access to unexported fields.
Treat this as a first-class option and implement AllowUnexported
in terms of the new Exporter option.
The new Exporter option:
* Better matches the existing style of top-level options
both by name (e.g., Comparer, Transformer, and Reporter)
and by API style (all accept a function).
* Is more flexible as it enables users to functionally
implement AllowAllUnexported by simply doing:
Exporter(func(reflect.Type) bool { return true })
Fixes #40
=> Add Exporter option

cmp/compare.go, cmp/compare_test.go, cmp/options.go, cmp/path.go
Previously, trying to call Equal on a graph would result in a stack-overflow
due to infinite recursion traversing cycles on a graph.
While a vast majority of Go values are trees or acyclic graphs, there exist
a small number of cases where graph equality is required.
As such, we add cycle detection to Equal and define what it means for two graphs
to be equal. Contrary to reflect.DeepEqual, which declares two graphs to be
equal so long any cycle were encountered, we require two graphs to have
equivalent graph structures.
Mathematically speaking, a graph G is a tuple (V, E) consisting of the set of
vertices and edges in that graph. Graphs G1 and G2 are equal if V1 == V2,
E1 == E2, and both have the same root vertex (entry point into the graph).
When traversing G1 and G2, we remember a stack …
=> Add support for comparing graphs

README.md
The color of the shield banner is "Gopher Blue" as defined by
brand book referenced by the Go blog. See https://blog.golang.org/go-brand
=> Update README.md to use go.dev for documentation

cmp/compare_test.go
Add because `reporterTests` was missing from `TestDiff`.
Fixes #197.
=> Add reporterTests to TestDiff

cmp/compare_test.go, cmp/testdata/diffs
Refactor the unit tests to read the diffs from a file
rather than being stored as a Go string literal.
The advantage of using a golden file is to ease
updating the diffs whenever the reporter output is changed.
=> Refactor tests to use golden test files

cmp/report_compare.go, cmp/report_reflect.go, cmp/report_slices.go, cmp/testdata/diffs
Since byte is an alias for uint8, format it in hex.
Fixes #185.
=> Fix uint to format in decimal

cmp/cmpopts/struct_filter.go, cmp/cmpopts/util_test.go
Modify IgnoreFields to permit the specification of unexported fields.
To avoid a bug with reflect.Type.FieldByName, we disallow forwarding
on unexported fields. See https://golang.org/issue/4876 for details.
Fixes #196
=> Permit use of IgnoreFields with unexported fields

cmp/compare.go
Diff is most often used in tests where the expected outcome
is equality (and thus no reported difference). Optimize for this
situation by performing a fast-pass equality check and only fall
back on constructing a report if inequal.
=> Optimize Diff for frequent equality

cmp/compare.go, cmp/compare_test.go, cmp/export_panic.go, cmp/export_unsafe.go, cmp/path.go, cmp/report_reflect.go
The current implementation for forcibly exporting fields relies on
the reflect.Value.Addr method for the parent struct value,
where it copies a non-addressable struct onto to the heap so
that it is addressable. However, this action leaks a subtle detail
of how the internal implementation works since the accessed field
for within a struct is only addressable if and only if the
parent struct is also addressable.
Modify the implementation to avoid leaking this implementation detail
by shallow copying the accessed unexported field to remove any
notion of addressability if the parent struct is also unaddressable.
Fixes #181
=> Avoid leaking implementation details of the exporter

cmp/compare_test.go, cmp/export_unsafe.go
A shallow copy with reflect.ValueOf(v.Interface()) does not work
if v is a nil interface value. Special case the edge case by
checking for a nil value and create a new one use reflect.Zero.
=> Fix exporter to handle nil interface values

cmp/internal/diff/diff.go, cmp/internal/diff/diff_test.go
The reporter output is documented as unstable.
The API for custom reporters also specifies that the diffing of
slices is unstable.
Introduce deliberate instability to the diffing algorithm so that
we have the flexibility to improve it in the future.
The current algorithm optimizes for speed, rather than optimality,
so there is much room for improvement.
=> Introduce deliberate instability to difference output

cmp/compare_test.go, cmp/report_compare.go, cmp/report_slices.go, cmp/report_text.go, cmp/testdata/diffs
For large slices, arrays, and maps, the reporter can be unreadable
if there are many differences. Limit the number of results to some
reasonable maximum.
=> Limit number of printed differences for variable-length composites

cmp/compare_test.go, cmp/example_test.go, cmp/report_compare.go, cmp/report_reflect.go, cmp/report_slices.go, cmp/testdata/diffs
A common complaint is that the reporter it prints out too much
irrelevant information, resulting in a low signal-to-noise ratio.
Improve this metric by imposing a verbosity limit. For nodes that
are equal, we set the verbosity level is a lower value than when
the nodes are inequal.
Other minor changes:
* Adjust heuristic for triple-quote usage to operate on more cases.
* Elide type more aggressively for equal nodes.
* Printing the address for a slice includes the length and capacity.
* The pointed-at value for map keys are printed.
=> Limit verbosity of reporter output

cmp/compare_test.go, cmp/internal/teststructs/foo1/foo.go, cmp/internal/teststructs/foo2/foo.go, cmp/internal/value/name.go, cmp/internal/value/name_test.go, cmp/report_compare.go, cmp/report_reflect.go, cmp/report_slices.go, cmp/report_text.go, cmp/testdata/diffs
The reporter tries to aggresively elide data that is not interesting
to the user. However, doing so many result in an output that does not
visually indicate the difference between semantically different objects.
This CL modifies the reporter try increasingly verbose settings until
two different objects are formatted differently.
=> Disambiguate reporter output

cmp/cmpopts/ignore.go
The function now handles unexported fields since #203.
=> Fix documentation on IgnoreFields

cmp/compare_test.go, cmp/testdata/diffs
Provide a unique name for every test case.
Provide a reason for every test case.
The purpose of a unique name is so that insertion/removal of a
case does not cause all subsequent names to suddenly shift,
causing a larger number of differences in testdata/diffs.
=> Update test case names

cmp/internal/value/pointer_purego.go, cmp/internal/value/pointer_unsafe.go, cmp/report.go, cmp/report_compare.go, cmp/report_references.go, cmp/report_reflect.go, cmp/report_slices.go, cmp/report_text.go, cmp/testdata/diffs
Previously, the reporter could handle formatting values with cycles
in that it did not crash with a stack overflow. However, the output
was not particularly understandable as it did not surface to the user
why a particular value was truncated, and if it was truncated due
to a cyclic reference, what was the referent.
This change annotates the reporter tree with pointer information
so that a later pass can inject reference information if it is needed
to produce more understandable output.
=> Improve reporting of values with cycles

cmp/compare_test.go, cmp/report_reflect.go, cmp/testdata/diffs
If a panic occurs while calling String or Error,
the reporter recovers from it and ignores it,
proceeding with its usual functionality for formatting a value.
=> Swallow panic when calling String or Error

cmp/cmpopts/ignore.go, cmp/cmpopts/struct_filter.go, cmp/cmpopts/util_test.go
Fixed panic message more specifically.
With this fix, you can see that IgnoreUnexported only supports a struct without the user having to look at the code.
=> Fixed panic message in IgnoreUnexported

cmp/compare_test.go, cmp/report_reflect.go, cmp/testdata/diffs
For strings, []bytes containing text data, Error method output, and
String method output, use the triple-quoted syntax.
This improves readability by presenting the data more naturally
compared to a single-line quoted string with many escaped characters.
=> Use triple-quote formatting for multiline strings

cmp/compare.go
Fix the doc about the cmp.Diff method. It was mentioning the plus or minus sign being printed if, respectively, the field was added to x or removed to y, but both things are equivalent. The sign change if a field is removed or added from y alone.
=> Update compare.go documentation

cmp/compare_test.go, cmp/options.go
If cmp panics because it is trying to access an unexported field,
specially suggest the use of cmpopts.EquateErrors if the parent type
implements the error interface.
Fixes #233
=> Suggest use of cmpopts.EquateErrors

cmp/cmpopts/example_test.go
I was struggling to figure out how to use IgnoreFields initially so I figured an example would be helpful.  I've essentially ripped off the example from the parent module with a proper copy paste job for now with a quick example.
If you can suggest a better way to do it, I'd be happy to clean up the code.
I suspect I could also make the example clearer, but I'd quite like to clean up the code before going too far.
=> Create a simple example for the IgnoreFields

cmp/cmpopts/ignore.go, cmp/internal/value/iface.go, cmp/internal/value/iface_test.go, cmp/options.go
In Go1.16, the reflect.Type.NumMethod method will no longer report
unexported fields, matching the documented behavior on the method.
This means that t.NumMethod() == 0 is no longer a reliable means
to detect whether an interface type is the empty interface or not.
Fix the code to check whether the empty interface itself implements
the target type.
=> Adjust for reflect.Type.NumMethod change in Go1.16

cmp/internal/diff/diff.go, cmp/internal/diff/diff_test.go
A previous attempt to add non-determinism to the diffing algorithm
unfortunately broke the algorithm for half the cases.
This change modifies the algorithm to truly switch between starting
with a forward search versus a reverse search.
The main for-loop of Difference would switch repeatedly between
performing a forward search, then a reverse search, and vice-versa.
Since we can't jump into the middle of a for-loop to start with the
reverse search first, we use a series of labels and goto statements
to accomplish the same effect.
Fixes #238
=> Fix non-determinism in diffing algorithm

cmp/cmpopts/equate.go, cmp/cmpopts/errors_go113.go, cmp/cmpopts/errors_xerrors.go
Use the standard definition of errors.Is to implement compareErrors with
≥go1.13. Retain the implementation using golang.org/x/xerrors for versions <go1.13.
This will allow packages using newer Go versions and already relying on
the errors package to get rid of the transitive dependency on
golang.org/x/xerrors.
=> cmp/cmpopts: use errors.Is with ≥go1.13 in compareErrors

.github/workflows/test.yml
Add Go 1.16 to the GitHub actions test coverage matrix.
Also switch the `gofmt` check to only run on Go 1.16, i.e. the latest
supported version.
=> Run tests on Go 1.16

cmp/compare_test.go, cmp/report_slices.go, cmp/testdata/diffs
Specialized diffing strings and slices should occur for
interface types where both values have the same concrete type.
This is especially relevant for protocmp.Transform,
which transforms every proto.Message as a map[string]interface{}.
=> De-virtualize interfaces for specialized diffing

cmp/path.go
=> Fix typo in path.go

cmp/compare_test.go, cmp/report_slices.go, cmp/testdata/diffs
Avoid diffing by lines if it turns out to be significantly less
efficient than diffing by bytes.
Before this change:
```patch
(
"""
- 	d5c14bdf6bac81c27afc5429500ed750
- 	25483503b557c606dad4f144d27ae10b
- 	90bdbcdbb6ea7156068e3dcfb7459244
- 	978f480a6e3cced51e297fbff9a506b7
+ 	Xd5c14bdf6bac81c27afc5429500ed750
+ 	X25483503b557c606dad4f144d27ae10b
+ 	X90bdbcdbb6ea7156068e3dcfb7459244
+ 	X978f480a6e3cced51e297fbff9a506b7
"""
)
```
After this change:
```patch
strings.Join({
+ 	"X",
"d5c14bdf6bac81c27afc5429500ed750\n",
+ 	"X",
"25483503b557c606dad4f144d27ae10b\n",
+ 	"X",
"90bdbcdbb6ea7156068e3dcfb7459244\n",
+ 	"X",
"978f480a6e3cced51e297fbff9a506b7\n",
}, "")
```
=> Avoid diffing by lines if inefficient

cmp/compare_test.go, cmp/report_slices.go, cmp/testdata/diffs
The previous heuristic of treating strings as binary data
if it contains any invalid UTF-8 was too strict.
Loosen the heuristic to check if most of the characters
are printable text.
Fixes #257
=> Print as text if mostly text

cmp/compare_test.go, cmp/example_test.go
Address some minor issues flagged by staticcheck.
None of these affect the correctness of the package.
=> Fix staticcheck findings

cmp/report_slices.go
Rename the shadowed variable i to j for better readability.
=> Avoid shadowing variable

cmp/compare_test.go, cmp/report_reflect.go, cmp/testdata/diffs
There are two bugs being fixed:
1.  The hueristic for whether a slice of byte looks like text
should check whether a rune IsPrint OR IsSpace, and not both.
Only a single rune (i.e., U+0020) ever satisfies both conditions.
Previously, it would print as:
```
MyBytes{0x68, 0x65, 0x6c, 0x6c, 0x6f}
```
and now it would now print as:
```
MyBytes(MyBytes("hello"))
```
2.  If we're printing as string, then we should set skipType=true
since we already explicitly format the value with the type.
Previously, it would print as:
```
MyBytes(MyBytes("hello"))
```
and now it would now print as:
```
MyBytes("hello")
```
=> Fix textual printing of byte slices

.github/workflows/test.yml, cmp/cmpopts/errors_go113.go, cmp/cmpopts/errors_xerrors.go, cmp/export_panic.go, cmp/export_unsafe.go, cmp/internal/diff/debug_disable.go, cmp/internal/diff/debug_enable.go, cmp/internal/value/pointer_purego.go, cmp/internal/value/pointer_unsafe.go
Starting with Go 1.17, //go:build lines are preferred over // +build
lines, see https://golang.org/doc/go1.17#build-lines and
https://golang.org/design/draft-gobuild for details.
This change was generated by running Go 1.17 go fmt ./... which
automatically adds //go:build lines based on the existing // +build
lines.
Also update the corresponding GitHub action to use Go 1.17 gofmt.
=> Add //go:build lines

cmp/cmpopts/example_test.go, cmp/compare_test.go, cmp/example_test.go, cmp/report_compare.go, cmp/report_reflect.go, cmp/testdata/diffs
If a slice of bytes is mostly text, format them as text
instead of as []byte literal with hexadecimal digits.
Avoid always printing the type. This is technically invalid Go code,
but is unnecessary in many cases since the type is inferred
from the parent concrete type.
Fixes #272
=> Use string formatting for slice of bytes

cmp/path.go
The value.TypeString function is what the rest of the package uses
and is slightly cleaner than using reflect.Type.String.
Updates #305
=> Use value.TypeString in PathStep.String

cmp/compare_test.go, cmp/report_slices.go, cmp/testdata/diffs
If the string has many characters that require escape sequences to print,
then we need to take that into consideration and avoid byte-by-byte diffing.
=> Adjust heuristic for line-based versus byte-based diffing

cmp/cmpopts/equate.go, cmp/cmpopts/ignore.go, cmp/cmpopts/sort.go, cmp/cmpopts/xform.go, cmp/compare.go, cmp/example_test.go, cmp/options.go, cmp/path.go
GoDoc now supports hot linking to specific Go identifiers. Use that feature to enhance the usability of cmp docs.
Since cmp lacks a direct dependency on cmpopts,
you are forced to use the fully-qualified import path to references identifiers in the cmpopts package.
It can future improvements to the go/doc to handle this case, either by rendering the doc with short form,
or by detecting the use of cmpopts from the unit tests as well (since those can break circular dependencies).
=> Use of hotlinking of Go identifiers

.github/workflows/test.yml, cmp/cmpopts/equate.go, cmp/cmpopts/util_test.go, cmp/options.go
This helper function makes it easier to specify that comparable types are safe to directly compare with the == operator in Go.
The API does not use generics as it follows existing options like cmp.AllowUnexported, cmpopts.IgnoreUnexported, or cmpopts.IgnoreTypes.
While generics provides type safety, the user experience is not as nice. Our current API allows multiple types to be specified:
```go
cmpopts.EquateComparable(netip.Addr{}, netip.Prefix{})
```
While generics would not allow variadic arguments:
```go
cmpopts.EquateComparable[netip.Addr]()
cmpopts.EquateComparable[netip.Prefix]()
```
Bump mininimum supported Go to 1.18 for net/netip type. Start testing on Go 1.21.
Fixes #339
=> Add cmpopts.EquateComparable

.github/workflows/test.yml, cmp/cmpopts/sort.go, cmp/cmpopts/util_test.go, cmp/internal/function/func.go, go.mod
The SortSlices and SortMaps options predate generics and
accept an interface{}, so it is possible with reflection to support other function signatures than "func(T, T) bool".
In particular, the Go ecosystem is increasingly moving towards "func(T, T) int" as the signature for ordering as evidenced by the newer slices.SortFunc function in stdlib.
Thus, modernize cmpopts by supporting "func(T, T) int".
Fixes #365
=> Support compare functions with SortSlices and SortMaps

cmp/options.go
While we do not provide 1st class handling of protobuf messages, we can at least detect whether the type is a proto.Message and refer the user to the correct package to use to handle protobuf messages with cmp.Equal.
=> Detect proto.Message types when failing to export a field
